import locale from '@/locales/zh-CN';

export const modelName = 'LOPA';
export const listName = 'list';
export const detailName = 'detail';
export const listApi = 'LOPA/getList';
export const detailApi = 'LOPA/getDetail';
export const addApi = 'LOPA/add';
export const editApi = 'LOPA/edit';
export const deleteApi = 'LOPA/delete';
export const detailCode = 'riskControl.LOPA.detail';
export const addCode = 'riskControl.LOPA.add';
export const editCode = 'riskControl.LOPA.edit';
export const deleteCode = 'riskControl.LOPA.delete';
export const listPath = '/risk-control/LOPA/list';
export const detailPath = '/risk-control/LOPA/detail';
export const addPath = '/risk-control/LOPA/add';
export const editPath = '/risk-control/LOPA/edit';
export const parentLocale = locale['menu.riskControl'];
export const listLocale = locale['menu.riskControl.LOPA.list'];
export const detailLocale = locale['menu.riskControl.LOPA.detail'];
export const addLocale = locale['menu.riskControl.LOPA.add'];
export const editLocale = locale['menu.riskControl.LOPA.edit'];
