import NewVideoPlay from '@/pages/BigPlatform/NewFireControl/section/NewVideoPlay';
import { SetDrawer } from '@/pages/BigPlatform/Safety/Company3/components';

export {
  AlarmDynamicDrawer,
  AlarmDynamicMsgDrawer,
  CheckDrawer,
  CheckingDrawer,
  CheckWorkOrder,
  CompanyInfo,
  CurrentHiddenDanger,
  DrawerHiddenDangerDetail,
  DrawerOfFireAlarm,
  ElectricityDrawer,
  ElectricityMonitor,
  FaultMessageDrawer,
  FireDevice,
  FireDevice1,
  FireFlowDrawer,
  FireMonitorFlowDrawer,
  FireMonitoring,
  FourColor,
  GasFlowDrawer,
  MaintenanceCheckDrawer,
  MaintenanceCount,
  MaintenanceDrawer,
  MaintenanceMsgDrawer,
  Messages,
  NewWorkOrderDrawer,
  OnekeyFlowDrawer,
  Pie,
  PointInspectionCount,
  PointInspectionDrawer,
  PointPositionName,
  ResetHostsDrawer,
  RiskDrawer,
  Section,
  SmokeDrawer,
  SmokeFlowDrawer,
  SmokeMonitor,
  StatisticsOfFireControl,
  TabSection,
  VideoSurveillance,
  WaterMonitor,
  WaterSystemDrawer,
  WorkOrderDrawer,
} from '@/pages/BigPlatform/NewUnitFireControl/Section/Components';

export {
  NewVideoPlay,
  SetDrawer,
}
