export const NAMESPACE = 'HAZOP';
export const LIST_NAME = 'list';
export const DETAIL_NAME = 'detail';
export const LIST_API = `${NAMESPACE}/getList`;
export const DETAIL_API = `${NAMESPACE}/getDetail`;
export const ADD_API = `${NAMESPACE}/add`;
export const EDIT_API = `${NAMESPACE}/edit`;
export const DELETE_API = `${NAMESPACE}/delete`;
export const DETAIL_CODE = `riskControl.${NAMESPACE}.detail`;
export const ADD_CODE = `riskControl.${NAMESPACE}.add`;
export const EDIT_CODE = `riskControl.${NAMESPACE}.edit`;
export const DELETE_CODE = `riskControl.${NAMESPACE}.delete`;
export const LIST_PATH = '/risk-control/HAZOP/list';
export const DETAIL_PATH = '/risk-control/HAZOP/detail';
export const ADD_PATH = '/risk-control/HAZOP/add';
export const EDIT_PATH = '/risk-control/HAZOP/edit';
export const FORMAT = 'YYYY-MM-DD';
export const SHOW_TOTAL = total => `共 ${total} 条记录`;
export const GET_VALUE_FROM_EVENT = value =>
  value && { ...value, key: value.key || value.value, value: value.key || value.value };
