import locale from '@/locales/zh-CN';

export const modelName = 'HAZOP';
export const listName = 'list';
export const detailName = 'detail';
export const listApi = 'HAZOP/getList';
export const detailApi = 'HAZOP/getDetail';
export const addApi = 'HAZOP/add';
export const editApi = 'HAZOP/edit';
export const deleteApi = 'HAZOP/delete';
export const detailCode = 'riskControl.HAZOP.detail';
export const addCode = 'riskControl.HAZOP.add';
export const editCode = 'riskControl.HAZOP.edit';
export const deleteCode = 'riskControl.HAZOP.delete';
export const listPath = '/risk-control/HAZOP/list';
export const detailPath = '/risk-control/HAZOP/detail';
export const addPath = '/risk-control/HAZOP/add';
export const editPath = '/risk-control/HAZOP/edit';
export const parentLocale = locale['menu.riskControl'];
export const listLocale = locale['menu.riskControl.HAZOP.list'];
export const detailLocale = locale['menu.riskControl.HAZOP.detail'];
export const addLocale = locale['menu.riskControl.HAZOP.add'];
export const editLocale = locale['menu.riskControl.HAZOP.edit'];
