export default {
  default: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '晶安智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
  },
  jiangxi: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '江溪街道智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
  },
  xuzhou: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '晶安智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
  },
  changshu: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '晶安智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
  },
};
