export default {
  default: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '晶安智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
    safetyGovernmentTitle: '晶安智慧安全云平台',
    location: {
      x: 120.401163,
      y: 31.560116,
      zoom: 13,
    },
  },
  jiangxi: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '江溪街道智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
    safetyGovernmentTitle: '江溪街道智慧安全云平台',
    location: {
      x: 120.401163,
      y: 31.560116,
      zoom: 13,
    },
  },
  xuzhou: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '徐州智慧安全平台',
    servicePhone: '400-928-5656',
    serviceSupport: '无锡晶安智慧科技有限公司',
    safetyGovernmentTitle: '徐州智慧安全云平台',
    location: {
      x: 117.407812,
      y: 34.501282,
      zoom: 14,
    },
  },
  changshu: {
    logo: '',
    mail: 'jazh@jingan-china.cn',
    mainWeb: 'https://www.jingan-china.cn',
    projectKey: 'v2_test',
    projectName: '常熟智慧安全平台',
    servicePhone: '400-928-3688',
    serviceSupport: '苏州晶程智慧科技有限公司',
    safetyGovernmentTitle: '常熟智慧安全云平台',
    location: {
      x: 120.848825,
      y: 31.639258,
      zoom: 13,
    },
  },
};
