import locale from '@/locales/zh-CN';

export const modelName = '$namespace';
export const listName = 'list';
export const detailName = 'detail';
export const listApi = '$namespace/getList';
export const detailApi = '$namespace/getDetail';
export const addApi = '$namespace/add';
export const editApi = '$namespace/edit';
export const deleteApi = '$namespace/delete';
export const detailCode = '$detailCode';
export const addCode = '$addCode';
export const editCode = '$editCode';
export const deleteCode = '$deleteCode';
export const listPath = '$listPath';
export const detailPath = '$detailPath';
export const addPath = '$addPath';
export const editPath = '$editPath';
export const parentLocale = locale['$parentLocale'];
export const listLocale = locale['$listLocale'];
export const detailLocale = locale['$detailLocale'];
export const addLocale = locale['$addLocale'];
export const editLocale = locale['$editLocale'];
