import locale from '@/locales/zh-CN';

export const NAMESPACE = '$namespace';
export const LIST_NAME = 'list';
export const DETAIL_NAME = 'detail';
export const LIST_API = `$namespace/getList`;
export const DETAIL_API = `$namespace/getDetail`;
export const ADD_API = `$namespace/add`;
export const EDIT_API = `$namespace/edit`;
export const DELETE_API = `$namespace/delete`;
export const LIST_CODE = '$listCode';
export const DETAIL_CODE = '$detailCode';
export const ADD_CODE = '$addCode';
export const EDIT_CODE = '$editCode';
export const DELETE_CODE = '$deleteCode';
export const LIST_PATH = '$listPath';
export const DETAIL_PATH = '$detailPath';
export const ADD_PATH = '$addPath';
export const EDIT_PATH = '$editPath';
export const PARENT_LOCALE = locale['$parentLocale'];
export const LIST_LOCALE = locale['$listLocale'];
export const DETAIL_LOCALE = locale['$detailLocale'];
export const ADD_LOCALE = locale['$addLocale'];
export const EDIT_LOCALE = locale['$editLocale'];
